### ISSUE TITLE
Can't run on last chrome

### ISSUE THREAD

**Issue by totty90** [qiao/fractal-terrain-generator#3]
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36 | WebGL 1.0 (OpenGL ES 2.0 Chromium) | WebKit | WebKit WebGL | WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium) Three.js:264
WebGL: INVALID_OPERATION: getAttribLocation: program not linked Three.js:741
WebGL: INVALID_OPERATION: getAttribLocation: program not linked Three.js:741
WebGL: INVALID_OPERATION: getUniformLocation: program not linked Three.js:741
WebGL: INVALID_OPERATION: getUniformLocation: program not linked Three.js:741
WebGL: INVALID_OPERATION: getUniformLocation: program not linked Three.js:741
WebGL: INVALID_OPERATION: getUniformLocation: program not linked Three.js:741
WebGL: INVALID_OPERATION: getUniformLocation: program not linked Three.js:741
WebGL: INVALID_OPERATION: getUniformLocation: program not linked Three.js:742
WebGL: INVALID_OPERATION: getUniformLocation: program not linked Three.js:742
WebGL: INVALID_OPERATION: getUniformLocation: program not linked Three.js:742
DEPRECATED: Camera hasn't been added to a Scene. Adding it... Three.js:283
Could not initialise shader
VALIDATE_STATUS: false, gl error [0] Three.js:340initMaterial Three.js:340m Three.js:241renderBuffer Three.js:275update Three.js:752render Three.js:748h Three.js:239render Three.js:283animate main.js:302
9WebGL: INVALID_OPERATION: getUniformLocation: program not linked Three.js:341
18WebGL: INVALID_OPERATION: getAttribLocation: program not linked Three.js:342
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
Could not initialise shader
VALIDATE_STATUS: false, gl error [1282] Three.js:340
38WebGL: INVALID_OPERATION: getUniformLocation: program not linked Three.js:341
18WebGL: INVALID_OPERATION: getAttribLocation: program not linked Three.js:342
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:281
WebGL: INVALID_OPERATION: useProgram: program not valid Three.js:242
2WebGL: INVALID_OPERATION: drawElements: no valid shader program in use Three.js:282
WebGL: too many errors, no more errors will be reported to the console for this context.

**Comment by kenorb** [comment]
The same here at: http://qiao.github.io/fractal-terrain-generator/demo/
